### ISSUE TITLE
[BUG] No modules present in vanilla or Zeus Enhanced

### ISSUE THREAD

**Issue by AVESUM** [Walthzer/RID#11]
**Describe the bug**
Referencing how the UI in Zeus should look like in [this ](https://youtu.be/foNRV7Rr4XY) video I'm not able to start this mod properly as the Zeus WFAR category won't show. 

**To Reproduce**
1. Start ARMA 3DEN with CBA, ACE and RID. 
2. Place a blufor soldier with variable "zeus" and Zeus Game master module with owner "zeus". Allow all unofficial addons.
3. Play mission i MP.
4. Enter Zeus.

**Expected behavior**
WFAR category of modules visible in the right Zeus menu.

**Screenshots**
https://imgur.com/fNQZmKX

**Additional context**
If Achilles is required it should be specified in Steam mod page. 
If Achilles is required it would be great if support for ZEN Zeus Enhanced also is included in the mod.

**Comment by AVESUM** [comment]
Found the ArchillesModules.hpp. For ZEN: https://zen-mod.github.io/ZEN/#/frameworks/custom_modules

**Comment by Walthzer** [comment]
Good evening AVESUM,

Apologies for the late response. We had indeed forgotten to list Achilles as a requirement and hadn't yet realized that Zeus Enhanced compatibility would have been required. Both these issues are now fixed with above pull request. 

The Steam page will also be updated shortly.

**Comment by AVESUM** [comment]
Unfortunately this issue is still present even after Steam update.

**Comment by Walthzer** [comment]
Indeed. 
The issues has been found and fixed as of now.
